version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - tray_dev
    ports:
      - 3306:3306
    # volumes:
    #   - ./mysql:/var/lib/mysql
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tray_api
    depends_on:
      - mysql
    networks:
      - tray_dev
    # ports:
    #   - 3000:3000
    # volumes:
    #   - ./api:/usr/src/app
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: tray_ui
    depends_on:
      - api
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  tray_dev:
    driver: bridge
