version: '3.3'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - tray_dev
    ports:
      - 3306:3306
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tray_dev

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - .:/var/www
    networks:
      - tray_dev
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: tray_ui
    networks:
      - tray_dev
    depends_on:
      - api
    ports:
      - 5173:5173

    restart: unless-stopped

networks:
  tray_dev:
    driver: bridge
